language: node_js
node_js:
- '8'
before_install:
- npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
env:
  global:
    secure: Bdg3i0HqEwL1RLWLWCka8N6oZwrBJyJB3dT4zTTXhf+OJKrf1/Bafbi3nCGksM8piwnpcXa4QLH9UhMsm7HM5VNEtGDOQ7uSAEbs7qbzhzUh1CUZOItWc8zyzx4TXEQvnvh7v2Tw+8FBHSIYg3dTrdsMZJaMMXIsyIPCQJDg9unx8kON8wJKCTT8znNQfTRCHpW6kIM7bHBEw5GLq+xb4kjApvaDeK+uyNvPeQ9fWtafJFiCYyUaOfE/PmrYr231NuN6i/lJwbyLegLNIjJ31Su72gVp/wnqN5oGOcrpvgr0yxgwnazL+e8IJxyxl+513F9ZDuhevLMdFa5PngMJ3+Zu3YsVrRT80ULFCNMPAJGzQCi6Pu3vhCjHGQcsYRNjF1CbiSRfR0FMGZn6XNEMGt08X081ak+zckQ89Y0ULaeXhirDQEXTRkTSBm87XBuHTm9fBgS97q/BjhunxqVCF2F8j+HppOiJmaMGPQY29NfILHIbo/Ok/+2U/1Snwf1OUj+RpBAQBg4Ir+0ZC93wLrbeEaGyWmB3M81aJtEMfP8Ftm1Az4j1k2RQpBMoZVPgux821iWV586miIxEPq64aggv3qjO0DdM/9cn06eXNdhQP1nOMtEQ3K0iR0U4617HIMtiUk89LbPvV2jV+DZifdYEvw4iJb0g26ybvcHtg8A=
